# Generated by Django 5.0.4 on 2024-04-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0002_notatka_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notatka',
            name='urgency',
        ),
    ]
