# Generated by Django 5.0.4 on 2024-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0004_notatka_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notatka',
            name='urgency',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0),
        ),
    ]
