# Generated by Django 5.0.4 on 2024-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0005_alter_notatka_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notatka',
            name='urgency',
            field=models.CharField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, max_length=6),
        ),
    ]
