# Generated by Django 5.0.4 on 2024-04-23 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0006_alter_notatka_urgency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notatka',
            new_name='Note',
        ),
    ]
