# Generated by Django 4.2.11 on 2024-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0007_rename_notatka_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='urgency',
            field=models.CharField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default='Low', max_length=6),
        ),
    ]
