# Generated by Django 4.2.11 on 2024-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0008_alter_note_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='urgency',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=6),
        ),
    ]
