# Generated by Django 4.2.11 on 2024-04-23 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplikacjaNotatki', '0009_alter_note_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='urgency',
            field=models.CharField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], max_length=6),
        ),
    ]
