# Generated by Django 4.2.11 on 2024-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0010_alter_note_author_alter_note_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
