# Generated by Django 4.2.11 on 2024-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0011_alter_note_urgency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-urgency',)},
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
