# Generated by Django 4.2.11 on 2024-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0012_alter_note_options_alter_note_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('urgency',)},
        ),
        migrations.AlterField(
            model_name='note',
            name='urgency',
            field=models.CharField(choices=[('1 - High', 'High'), ('2 - Medium', 'Medium'), ('3 - Low', 'Low')], default='3 - Low', max_length=10),
        ),
    ]
