# Generated by Django 4.2.11 on 2024-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0013_alter_note_options_alter_note_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='urgency',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='3', max_length=10),
        ),
    ]
