# Generated by Django 4.2.11 on 2024-05-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0014_alter_note_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated',
        ),
    ]
