# Generated by Django 4.2.13 on 2024-05-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0016_note_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated',
        ),
    ]
