# Generated by Django 4.2.13 on 2024-05-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaNotatki', '0020_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('urgency', 'created')},
        ),
    ]
